# Generated by Django 4.2.1 on 2023-07-26 05:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("Ourblog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="poster",
            name="Post_date",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
