# Generated by Django 4.2.1 on 2023-07-26 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Ourblog", "0002_poster_post_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="poster",
            name="category",
            field=models.CharField(default="Uncategorised", max_length=255),
        ),
        migrations.AddField(
            model_name="poster",
            name="title_tag",
            field=models.CharField(default="Subtitle", max_length=255),
        ),
    ]
