# Generated by Django 4.2.1 on 2023-07-26 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Ourblog", "0004_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="poster",
            name="category",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="poster",
            name="title_tag",
            field=models.CharField(default="", max_length=255),
        ),
    ]
