# Generated by Django 4.2.1 on 2023-07-30 09:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Ourblog", "0006_poster_likes"),
    ]

    operations = [
        migrations.AddField(
            model_name="poster",
            name="unlikes",
            field=models.ManyToManyField(
                related_name="unBlog_post", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
