# Generated by Django 4.2.1 on 2023-07-30 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Ourblog", "0007_poster_unlikes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="poster",
            name="unlikes",
        ),
    ]
