# Generated by Django 4.2.1 on 2023-07-30 11:38

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Ourblog", "0008_remove_poster_unlikes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="poster",
            name="body",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
