# Generated by Django 4.2.1 on 2023-07-30 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Ourblog", "0009_alter_poster_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="poster",
            name="snippet",
            field=models.CharField(
                default="click above to read the article", max_length=255
            ),
        ),
    ]
