# Generated by Django 4.2.3 on 2023-08-01 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Ourblog", "0010_poster_snippet"),
    ]

    operations = [
        migrations.AddField(
            model_name="poster",
            name="header_image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
