# Generated by Django 4.2.3 on 2023-08-01 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Ourblog", "0012_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="poster",
            name="header_image",
            field=models.ImageField(
                blank=True, default="", null=True, upload_to="images/"
            ),
        ),
    ]
