# Generated by Django 4.2.3 on 2023-08-01 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Ourblog", "0013_alter_poster_header_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="poster",
            name="header_image",
            field=models.ImageField(default="", null=True, upload_to="images/"),
        ),
    ]
