# Generated by Django 4.2.3 on 2023-08-03 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Ourblog", "0019_remove_profile_user_profile_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="bio",
            field=models.TextField(default="", null=True),
        ),
    ]
